pipeline {
    agent none

    tools {
        maven 'test-maven'
    }
    environment {
        Dev_name_Gloabal = "Sudipta Mukherjee"
    }
    parameters {
        string defaultValue: 'SUDIPTA MUKHERJEE', name: 'FIRST_NAME'
    }


    stages {
        stage('Build-maven-app-agent-2') {
             environment {
                    stage_specific_env = "Stage-Specific-Value_For Build-maven-app"
                }
            agent { label 'linux-agent-1' }
            steps {
                echo 'Building start...'
                sh 'mvn clean package -DskipTests'
                echo 'Building end...'
               
                 echo "This is globally access value--->>>>${env.Dev_name_Gloabal}"
                echo "${env.stage_specific_env}" 
                echo "Parameter value is --->>>${params.FIRST_NAME}"


                // stash name: 'sudipta-app-jar', includes: 'target/my-app-1.0-SNAPSHOT.jar'
            }
           
        }

        stage('Test-maven-app') {
            agent { label 'linux-agent-1' }
            steps {
                echo 'Testing start...'
                sh 'mvn test'

                echo 'Testing end...'
            }

         post {
                success {
                    echo 'Archiving artifacts'
                    // archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                    stash name: 'sudipta-app-jar', includes: 'target/my-app-1.0-SNAPSHOT.jar'
                }
            }
        }

        // stage('Deploy-maven-app') {
        //     steps {
        //         echo 'Deploying...'
        //     }
        // }
    }
}
