pipeline {
    agent {
        label ' linux-agent-2 '
    }  

    stages {
        stage('Build-maven-app-agent-2') {
            steps {
                echo 'Building start...'
                sh 'mvn clean package'
                echo 'Building end...'
            }
        }
        stage('Test-maven-app') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy-maven-app') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}